### ISSUE TITLE
Error minifying npmjs.com

### ISSUE THREAD

**Issue by maltsev** [maltsev/htmlnano#23]
Error minifying [npmjs.com main page](https://gist.github.com/maltsev/ba3affc8aa57c29c13fe):
```js
{ message: 'Unexpected token: punc (:)',
  filename: 0,
  line: 1,
  col: 13,
  pos: 13,
  stack: `Error
at new JS_Parse_Error (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1524:18)
at js_error (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1532:11)
at croak (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2023:9)
at token_error (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2031:9)
at unexpected (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2037:9)
at semicolon (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2057:43)
at simple_statement (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2237:73)
at eval (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2090:47)
at eval (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2070:24)
at block_ (eval at <anonymous> (/Users/maltsev/dev/js/htmlnano/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2350:20)` }
```

**Comment by maltsev** [comment]
Fixed.
